#!/usr/bin/env python3
"""Run this collection's installer from any directory.

`skills setup-path` writes small launcher shims into a directory on PATH. Each
shim remembers where this checkout lives, so `skills install NAME` works from
inside any project and defaults to a repo-level install of the current working
directory -- `./.agents/skills` and `./.claude/skills`.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path
from typing import Mapping, Optional, Sequence

REPO_ROOT = Path(__file__).resolve().parent
if str(REPO_ROOT) not in sys.path:
    # Importing the installer keeps one implementation of root resolution,
    # backups, and receipts. This CLI only decides which arguments to hand it.
    sys.path.insert(0, str(REPO_ROOT))

import install  # noqa: E402


SHIM_NAME = "skills"
DEFAULT_BIN = Path.home() / ".local" / "bin"
PROFILE_MARKER = "# added by dm1681/skills setup-path"

SH_SHIM = """#!/usr/bin/env sh
# Generated by `skills setup-path` from @REPO@
# Regenerate after moving or renaming that checkout.
set -eu

REPO=@REPO_QUOTED@
CLI="$REPO/skills_cli.py"

if command -v uv >/dev/null 2>&1; then
  exec uv run --project "$REPO" --python 3.12 "$CLI" "$@"
fi

for interpreter in python3 python; do
  if command -v "$interpreter" >/dev/null 2>&1 \\
    && "$interpreter" -c 'import sys; raise SystemExit(sys.version_info < (3, 9))' \\
      >/dev/null 2>&1; then
    exec "$interpreter" "$CLI" "$@"
  fi
done

printf '%s\\n' 'uv or Python 3.9 or newer is required.' >&2
exit 127
"""

# Batch expands %ERRORLEVEL% when a parenthesized block is parsed, not when it
# runs, so every branch below is a label rather than an if/else block. Inside
# parentheses each `exit /b %ERRORLEVEL%` would return the code from *before*
# the command it is meant to report on.
CMD_SHIM = """@echo off
rem Generated by "skills setup-path" from @REPO@
rem Regenerate after moving or renaming that checkout.
setlocal
set "REPO=@REPO@"
set "CLI=%REPO%\\skills_cli.py"

where uv >nul 2>&1
if not errorlevel 1 goto run_uv
goto try_py

:run_uv
uv run --project "%REPO%" --python 3.12 "%CLI%" %*
exit /b %ERRORLEVEL%

:try_py
where py >nul 2>&1
if errorlevel 1 goto try_python
py -3 -c "import sys; raise SystemExit(sys.version_info < (3, 9))" >nul 2>&1
if errorlevel 1 goto try_python
py -3 "%CLI%" %*
exit /b %ERRORLEVEL%

:try_python
where python >nul 2>&1
if errorlevel 1 goto missing
python -c "import sys; raise SystemExit(sys.version_info < (3, 9))" >nul 2>&1
if errorlevel 1 goto missing
python "%CLI%" %*
exit /b %ERRORLEVEL%

:missing
echo uv or Python 3.9 or newer is required.>&2
exit /b 127
"""


def _sh_quote(value: str) -> str:
    return "'" + value.replace("'", "'\\''") + "'"


def sh_shim(repo: Path) -> str:
    # Forward slashes so the shim reads the same under Git Bash, WSL, and a
    # POSIX shell; Windows accepts them everywhere a path is expected.
    posix = str(repo).replace("\\", "/")
    return SH_SHIM.replace("@REPO_QUOTED@", _sh_quote(posix)).replace("@REPO@", posix)


def cmd_shim(repo: Path) -> str:
    return CMD_SHIM.replace("@REPO@", str(repo))


def shims(repo: Path, bin_dir: Path) -> list:
    """Return `(path, content, newline, executable)` for each launcher needed.

    Windows gets both: `skills.cmd` for PowerShell and cmd.exe, and the
    extensionless `skills` for Git Bash, which cannot run a batch file.
    """
    files = [(bin_dir / SHIM_NAME, sh_shim(repo), "\n", True)]
    if os.name == "nt":
        files.append((bin_dir / (SHIM_NAME + ".cmd"), cmd_shim(repo), "\r\n", False))
    return files


def write_shims(repo: Path, bin_dir: Path, dry_run: bool = False) -> list:
    """Write every launcher, returning `(path, status)` for each."""
    results = []
    for path, content, newline, executable in shims(repo, bin_dir):
        if path.is_file() and path.read_text(encoding="utf-8") == content:
            results.append((path, "unchanged"))
            continue
        if dry_run:
            results.append((path, "would write"))
            continue
        bin_dir.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8", newline=newline) as handle:
            handle.write(content)
        if executable:
            path.chmod(path.stat().st_mode | 0o111)
        results.append((path, "wrote"))
    return results


def path_entries(env: Mapping[str, str]) -> list:
    entries = []
    for item in env.get("PATH", "").split(os.pathsep):
        item = item.strip().strip('"')
        if not item:
            continue
        try:
            entries.append(Path(item).expanduser())
        except (OSError, ValueError):
            continue
    return entries


def path_contains(bin_dir: Path, env: Mapping[str, str]) -> bool:
    def key(path: Path) -> str:
        return os.path.normcase(os.path.normpath(str(path)))

    return any(key(entry) == key(bin_dir) for entry in path_entries(env))


def add_to_windows_path(bin_dir: Path, dry_run: bool = False) -> str:
    """Append `bin_dir` to the current user's PATH in the registry.

    Deliberately not `setx`, which silently truncates any PATH longer than
    1024 characters.
    """
    import winreg

    with winreg.OpenKey(winreg.HKEY_CURRENT_USER, "Environment") as key:
        try:
            current, kind = winreg.QueryValueEx(key, "Path")
        except FileNotFoundError:
            current, kind = "", winreg.REG_EXPAND_SZ
    if path_contains(bin_dir, {"PATH": current}):
        return "user PATH already contains %s" % bin_dir
    updated = (current.rstrip(os.pathsep) + os.pathsep + str(bin_dir)).lstrip(os.pathsep)
    if dry_run:
        return "would add %s to the user PATH" % bin_dir
    with winreg.OpenKey(
        winreg.HKEY_CURRENT_USER, "Environment", 0, winreg.KEY_SET_VALUE
    ) as key:
        winreg.SetValueEx(key, "Path", 0, kind, updated)
    _broadcast_environment_change()
    return "added %s to the user PATH" % bin_dir


def _broadcast_environment_change() -> None:
    """Tell already-running shells that the environment changed (best effort)."""
    try:
        import ctypes
        from ctypes import wintypes

        ctypes.windll.user32.SendMessageTimeoutW(
            wintypes.HWND(0xFFFF),  # HWND_BROADCAST
            0x001A,  # WM_SETTINGCHANGE
            wintypes.WPARAM(0),
            ctypes.c_wchar_p("Environment"),
            0x0002,  # SMTO_ABORTIFHUNG
            5000,
            None,
        )
    except (AttributeError, OSError, ValueError):
        pass


def profile_for(env: Mapping[str, str], home: Optional[Path] = None) -> Path:
    base = home if home is not None else Path.home()
    shell = os.path.basename(env.get("SHELL", ""))
    if shell == "zsh":
        return base / ".zshrc"
    if shell == "bash":
        return base / ".bashrc"
    return base / ".profile"


def add_to_posix_path(
    bin_dir: Path,
    env: Mapping[str, str],
    dry_run: bool = False,
    home: Optional[Path] = None,
) -> str:
    profile = profile_for(env, home)
    base = home if home is not None else Path.home()
    try:
        # Write $HOME rather than an absolute path so the profile stays portable
        # between machines with different user names.
        spelled = "$HOME/" + bin_dir.relative_to(base).as_posix()
    except ValueError:
        spelled = str(bin_dir)
    if profile.is_file() and PROFILE_MARKER in profile.read_text(encoding="utf-8"):
        return "%s already configured" % profile
    block = '\n%s\nexport PATH="%s:$PATH"\n' % (PROFILE_MARKER, spelled)
    if dry_run:
        return "would append the PATH line to %s" % profile
    profile.parent.mkdir(parents=True, exist_ok=True)
    with open(profile, "a", encoding="utf-8", newline="\n") as handle:
        handle.write(block)
    return "appended the PATH line to %s" % profile


def install_argv(
    names: Sequence[str],
    scope: str,
    project_dir: Path,
    agents: Sequence[str],
    mode: str,
    force: bool,
    dry_run: bool,
) -> list:
    """Build the `install.py` argument list this subcommand delegates to."""
    argv = [
        "--non-interactive",
        "--scope",
        scope,
        "--project-dir",
        str(project_dir),
        "--mode",
        mode,
    ]
    for agent in agents:
        argv.extend(("--agent", agent))
    for name in names:
        argv.extend(("--skill", name))
    if force:
        argv.append("--force")
    if dry_run:
        argv.append("--dry-run")
    return argv


def can_prompt() -> bool:
    return install.is_terminal(sys.stdin) and install.is_terminal(sys.stdout)


def open_dashboard(
    project_dir: Path,
    scope: str = "project",
    agents: Optional[Sequence[str]] = None,
    mode: str = "copy",
    guided: Optional[bool] = None,
) -> int:
    """Launch the Textual dashboard, or explain how to get it.

    `guided=None` lets the app decide: a destination with no install receipt
    gets the step-by-step flow, everything else gets the dashboard.
    """
    try:
        import skills_tui
    except ImportError as exc:  # pragma: no cover - depends on the environment
        raise install.InstallError(
            "the dashboard needs Textual (%s). Run this through uv, which "
            "provisions the locked environment automatically, or "
            "`pip install textual`. Naming skills directly -- "
            "`skills install NAME` -- needs no dependencies at all." % exc
        )
    return skills_tui.run(project_dir, scope, agents, mode, guided)


def command_list(args: argparse.Namespace) -> int:
    print("\n".join(install.available_skills()))
    return 0


def command_status(args: argparse.Namespace) -> int:
    """Report which managed skills need updating.

    Deliberately dependency-free: this is the answer a SessionStart hook or a
    CI job wants, and neither has a terminal for the dashboard nor a reason to
    need `textual` installed.
    """
    scope = "user" if args.user else "project"
    project_dir = args.project_dir.expanduser().resolve()
    roots = install.resolve_roots(
        args.agent, scope, Path.home(), project_dir, None
    )
    lines, pending = install.status_lines(roots, args.check_origin)
    print("\n".join(lines))
    return install.STATUS_ACTION_EXIT if pending else 0


def command_where(args: argparse.Namespace) -> int:
    print(REPO_ROOT)
    return 0


def command_install(args: argparse.Namespace) -> int:
    bundled = install.available_skills()
    names = list(args.name)
    if args.all:
        if names:
            raise install.InstallError("pass skill names or --all, not both")
        names = list(bundled)

    scope = "user" if args.user else "project"
    project_dir = args.project_dir.expanduser().resolve()
    if scope == "project" and not project_dir.is_dir():
        raise install.InstallError("project directory does not exist: %s" % project_dir)

    if not names:
        if not can_prompt():
            raise install.InstallError(
                "name at least one skill, or pass --all: there is no terminal "
                "to open the dashboard in, and installing every skill by "
                "default would put more in this project than you asked for. "
                "`skills list` shows what is available."
            )
        return open_dashboard(
            project_dir, scope, args.agent, args.mode, args.guided
        )

    unknown = sorted(set(names) - set(bundled))
    if unknown:
        raise install.InstallError("unknown skill: %s" % ", ".join(unknown))

    if scope == "user":
        # Some skills opt out of a machine-wide default because their
        # description costs every unrelated session context for no benefit.
        narrow = [name for name in names if not install.skill_global_default(name)]
        if narrow:
            print(
                "note: %s is not recommended machine-wide; it is meant for "
                "repo-level installs" % ", ".join(narrow),
                file=sys.stderr,
            )
    elif project_dir == REPO_ROOT:
        print(
            "note: installing into this collection's own checkout; "
            "run this from a project directory instead",
            file=sys.stderr,
        )

    return install.main(
        install_argv(
            names,
            scope,
            project_dir,
            args.agent,
            args.mode,
            args.force,
            args.dry_run,
        )
    )


def command_setup_path(args: argparse.Namespace) -> int:
    bin_dir = (args.bin or DEFAULT_BIN).expanduser()
    for path, status in write_shims(REPO_ROOT, bin_dir, args.dry_run):
        print("%-12s %s" % (status, path))

    if path_contains(bin_dir, os.environ):
        print("%s is already on PATH." % bin_dir)
        return 0

    if args.add_path:
        if os.name == "nt":
            print(add_to_windows_path(bin_dir, args.dry_run))
        else:
            print(add_to_posix_path(bin_dir, os.environ, args.dry_run))
        print("Open a new terminal for the change to take effect.")
        return 0

    print()
    print("%s is not on PATH. Add it with:" % bin_dir)
    print()
    print("    skills setup-path --add-path")
    print()
    if os.name == "nt":
        print("That edits the current user's PATH in the registry (not the")
        print("machine-wide value) and leaves an existing PATH of any length intact.")
    else:
        print('Or add `export PATH="%s:$PATH"` to your shell profile.' % bin_dir)
    return 0


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(
        prog="skills",
        description=(
            "Install skills from this collection into the current project, "
            "from any directory."
        ),
    )
    result.add_argument("--version", action="version", version="skills %s" % install.VERSION)
    subcommands = result.add_subparsers(dest="command")

    installer = subcommands.add_parser(
        "install",
        help="install skills into the current directory (repo-level by default)",
    )
    installer.add_argument("name", nargs="*", help="skill names; omit to choose interactively")
    installer.add_argument("--all", action="store_true", help="install every bundled skill")
    installer.add_argument(
        "--user",
        action="store_true",
        help="install machine-wide instead of into the project directory",
    )
    installer.add_argument("--project-dir", type=Path, default=Path.cwd())
    installer.add_argument(
        "--agent",
        action="append",
        default=[],
        metavar="NAME",
        help="universal, codex, cursor, copilot, claude, or all (repeatable; default all)",
    )
    installer.add_argument("--mode", choices=("copy", "link"), default="copy")
    guided = installer.add_mutually_exclusive_group()
    guided.add_argument(
        "--guided",
        dest="guided",
        action="store_true",
        help="force the step-by-step flow instead of the dashboard",
    )
    guided.add_argument(
        "--no-guided",
        dest="guided",
        action="store_false",
        help="go straight to the dashboard on a first install",
    )
    installer.set_defaults(guided=None)
    installer.add_argument("--force", action="store_true")
    installer.add_argument("--dry-run", action="store_true")
    installer.set_defaults(handler=command_install)

    listing = subcommands.add_parser("list", help="list bundled skills")
    listing.set_defaults(handler=command_list)

    where = subcommands.add_parser("where", help="print this checkout's path")
    where.set_defaults(handler=command_where)

    status = subcommands.add_parser(
        "status",
        help="report which installed skills differ from this checkout",
    )
    status.add_argument(
        "--user",
        action="store_true",
        help="check the machine-wide roots instead of this project's",
    )
    status.add_argument(
        "--agent",
        action="append",
        default=[],
        metavar="NAME",
        help="limit the check to one agent's skill directory",
    )
    status.add_argument("--project-dir", type=Path, default=Path.cwd())
    status.add_argument(
        "--check-origin",
        action="store_true",
        help="also fetch and report whether this checkout is behind origin",
    )
    status.set_defaults(handler=command_status)

    setup = subcommands.add_parser(
        "setup-path", help="write launcher shims so `skills` works from any directory"
    )
    setup.add_argument(
        "--bin",
        type=Path,
        default=None,
        metavar="DIR",
        help="directory to write the launchers into (default ~/.local/bin)",
    )
    setup.add_argument(
        "--add-path",
        action="store_true",
        help="also add that directory to your PATH",
    )
    setup.add_argument("--dry-run", action="store_true")
    setup.set_defaults(handler=command_setup_path)

    return result


def main(argv: Optional[Sequence[str]] = None) -> int:
    raw = list(sys.argv[1:] if argv is None else argv)
    arguments = parser().parse_args(raw)
    try:
        if getattr(arguments, "handler", None) is None:
            # A bare `skills` in a terminal means "show me what I have"; without
            # one there is nothing to show, so fall back to the help text.
            if not raw and can_prompt():
                return open_dashboard(Path.cwd())
            parser().print_help()
            return 2
        return arguments.handler(arguments)
    except KeyboardInterrupt:
        print("error: interrupted", file=sys.stderr)
        return 130
    except install.InstallError as exc:
        print("error: %s" % exc, file=sys.stderr)
        return 2
    except OSError as exc:
        print("error: %s" % exc, file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
