#!/usr/bin/env python3
"""Run this collection's installer from any directory.

`skills setup-path` writes small launcher shims into a directory on PATH. Each
shim remembers where this checkout lives, so `skills install NAME` works from
inside any project and defaults to a repo-level install of the current working
directory -- `./.agents/skills` and `./.claude/skills`.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from pathlib import Path
from typing import Mapping, Optional, Sequence

REPO_ROOT = Path(__file__).resolve().parent
if str(REPO_ROOT) not in sys.path:
    # Importing the installer keeps one implementation of root resolution,
    # backups, and receipts. This CLI only decides which arguments to hand it.
    sys.path.insert(0, str(REPO_ROOT))

import install  # noqa: E402
import inventory  # noqa: E402


SHIM_NAME = "skills"
DEFAULT_BIN = Path.home() / ".local" / "bin"
PROFILE_MARKER = "# added by dm1681/skills setup-path"

SH_SHIM = """#!/usr/bin/env sh
# Generated by `skills setup-path` from @REPO@
# Regenerate after moving or renaming that checkout.
set -eu

REPO=@REPO_QUOTED@
CLI="$REPO/skills_cli.py"

if command -v uv >/dev/null 2>&1; then
  exec uv run --project "$REPO" --python 3.12 "$CLI" "$@"
fi

for interpreter in python3 python; do
  if command -v "$interpreter" >/dev/null 2>&1 \\
    && "$interpreter" -c 'import sys; raise SystemExit(sys.version_info < (3, 9))' \\
      >/dev/null 2>&1; then
    exec "$interpreter" "$CLI" "$@"
  fi
done

printf '%s\\n' 'uv or Python 3.9 or newer is required.' >&2
exit 127
"""

# Batch expands %ERRORLEVEL% when a parenthesized block is parsed, not when it
# runs, so every branch below is a label rather than an if/else block. Inside
# parentheses each `exit /b %ERRORLEVEL%` would return the code from *before*
# the command it is meant to report on.
CMD_SHIM = """@echo off
rem Generated by "skills setup-path" from @REPO@
rem Regenerate after moving or renaming that checkout.
setlocal
set "REPO=@REPO@"
set "CLI=%REPO%\\skills_cli.py"

where uv >nul 2>&1
if not errorlevel 1 goto run_uv
goto try_py

:run_uv
uv run --project "%REPO%" --python 3.12 "%CLI%" %*
exit /b %ERRORLEVEL%

:try_py
where py >nul 2>&1
if errorlevel 1 goto try_python
py -3 -c "import sys; raise SystemExit(sys.version_info < (3, 9))" >nul 2>&1
if errorlevel 1 goto try_python
py -3 "%CLI%" %*
exit /b %ERRORLEVEL%

:try_python
where python >nul 2>&1
if errorlevel 1 goto missing
python -c "import sys; raise SystemExit(sys.version_info < (3, 9))" >nul 2>&1
if errorlevel 1 goto missing
python "%CLI%" %*
exit /b %ERRORLEVEL%

:missing
echo uv or Python 3.9 or newer is required.>&2
exit /b 127
"""


def _sh_quote(value: str) -> str:
    return "'" + value.replace("'", "'\\''") + "'"


def sh_shim(repo: Path) -> str:
    # Forward slashes so the shim reads the same under Git Bash, WSL, and a
    # POSIX shell; Windows accepts them everywhere a path is expected.
    posix = str(repo).replace("\\", "/")
    return SH_SHIM.replace("@REPO_QUOTED@", _sh_quote(posix)).replace("@REPO@", posix)


def cmd_shim(repo: Path) -> str:
    return CMD_SHIM.replace("@REPO@", str(repo))


def shims(repo: Path, bin_dir: Path) -> list:
    """Return `(path, content, newline, executable)` for each launcher needed.

    Windows gets both: `skills.cmd` for PowerShell and cmd.exe, and the
    extensionless `skills` for Git Bash, which cannot run a batch file.
    """
    files = [(bin_dir / SHIM_NAME, sh_shim(repo), "\n", True)]
    if os.name == "nt":
        files.append((bin_dir / (SHIM_NAME + ".cmd"), cmd_shim(repo), "\r\n", False))
    return files


def write_shims(repo: Path, bin_dir: Path, dry_run: bool = False) -> list:
    """Write every launcher, returning `(path, status)` for each."""
    results = []
    for path, content, newline, executable in shims(repo, bin_dir):
        if path.is_file() and path.read_text(encoding="utf-8") == content:
            results.append((path, "unchanged"))
            continue
        if dry_run:
            results.append((path, "would write"))
            continue
        bin_dir.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8", newline=newline) as handle:
            handle.write(content)
        if executable:
            path.chmod(path.stat().st_mode | 0o111)
        results.append((path, "wrote"))
    return results


def remove_shims(repo: Path, bin_dir: Path, dry_run: bool = False) -> list:
    """Inverse of write_shims, returning `(path, status)` for each launcher.

    `left` is a shim this checkout did not write. Another clone's launcher
    points somewhere else and is still in use; removing it because it shares a
    name would break a command this run has no business touching.
    """
    generated = "Generated by"
    posix_repo = str(repo).replace("\\", "/")
    results = []
    for path, content, _newline, _executable in shims(repo, bin_dir):
        if not path.is_file():
            results.append((path, "absent"))
            continue
        try:
            actual = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            actual = ""
        ours = actual == content or any(
            generated in line and posix_repo in line.replace("\\", "/")
            for line in actual.splitlines()
        )
        if not ours:
            results.append((path, "left"))
            continue
        if dry_run:
            results.append((path, "would remove"))
            continue
        path.unlink()
        results.append((path, "removed"))
    return results


def path_entries(env: Mapping[str, str]) -> list:
    entries = []
    for item in env.get("PATH", "").split(os.pathsep):
        item = item.strip().strip('"')
        if not item:
            continue
        try:
            entries.append(Path(item).expanduser())
        except (OSError, ValueError):
            continue
    return entries


def path_contains(bin_dir: Path, env: Mapping[str, str]) -> bool:
    def key(path: Path) -> str:
        return os.path.normcase(os.path.normpath(str(path)))

    return any(key(entry) == key(bin_dir) for entry in path_entries(env))


def add_to_windows_path(bin_dir: Path, dry_run: bool = False) -> str:
    """Append `bin_dir` to the current user's PATH in the registry.

    Deliberately not `setx`, which silently truncates any PATH longer than
    1024 characters.
    """
    import winreg

    with winreg.OpenKey(winreg.HKEY_CURRENT_USER, "Environment") as key:
        try:
            current, kind = winreg.QueryValueEx(key, "Path")
        except FileNotFoundError:
            current, kind = "", winreg.REG_EXPAND_SZ
    if path_contains(bin_dir, {"PATH": current}):
        return "user PATH already contains %s" % bin_dir
    updated = (current.rstrip(os.pathsep) + os.pathsep + str(bin_dir)).lstrip(os.pathsep)
    if dry_run:
        return "would add %s to the user PATH" % bin_dir
    with winreg.OpenKey(
        winreg.HKEY_CURRENT_USER, "Environment", 0, winreg.KEY_SET_VALUE
    ) as key:
        winreg.SetValueEx(key, "Path", 0, kind, updated)
    _broadcast_environment_change()
    return "added %s to the user PATH" % bin_dir


def _broadcast_environment_change() -> None:
    """Tell already-running shells that the environment changed (best effort)."""
    try:
        import ctypes
        from ctypes import wintypes

        ctypes.windll.user32.SendMessageTimeoutW(
            wintypes.HWND(0xFFFF),  # HWND_BROADCAST
            0x001A,  # WM_SETTINGCHANGE
            wintypes.WPARAM(0),
            ctypes.c_wchar_p("Environment"),
            0x0002,  # SMTO_ABORTIFHUNG
            5000,
            None,
        )
    except (AttributeError, OSError, ValueError):
        pass


def profile_for(env: Mapping[str, str], home: Optional[Path] = None) -> Path:
    base = home if home is not None else Path.home()
    shell = os.path.basename(env.get("SHELL", ""))
    if shell == "zsh":
        return base / ".zshrc"
    if shell == "bash":
        return base / ".bashrc"
    return base / ".profile"


def add_to_posix_path(
    bin_dir: Path,
    env: Mapping[str, str],
    dry_run: bool = False,
    home: Optional[Path] = None,
) -> str:
    profile = profile_for(env, home)
    base = home if home is not None else Path.home()
    try:
        # Write $HOME rather than an absolute path so the profile stays portable
        # between machines with different user names.
        spelled = "$HOME/" + bin_dir.relative_to(base).as_posix()
    except ValueError:
        spelled = str(bin_dir)
    if profile.is_file() and PROFILE_MARKER in profile.read_text(encoding="utf-8"):
        return "%s already configured" % profile
    block = '\n%s\nexport PATH="%s:$PATH"\n' % (PROFILE_MARKER, spelled)
    if dry_run:
        return "would append the PATH line to %s" % profile
    profile.parent.mkdir(parents=True, exist_ok=True)
    with open(profile, "a", encoding="utf-8", newline="\n") as handle:
        handle.write(block)
    return "appended the PATH line to %s" % profile


def remove_from_windows_path(bin_dir: Path, dry_run: bool = False) -> str:
    """Registry counterpart of add_to_windows_path."""
    import winreg

    with winreg.OpenKey(winreg.HKEY_CURRENT_USER, "Environment") as key:
        try:
            current, kind = winreg.QueryValueEx(key, "Path")
        except FileNotFoundError:
            return "the user PATH has no entry for %s" % bin_dir
    if not path_contains(bin_dir, {"PATH": current}):
        return "the user PATH has no entry for %s" % bin_dir
    keep = [
        item
        for item in current.split(os.pathsep)
        if item.strip()
        and os.path.normcase(os.path.normpath(item.strip().strip('"')))
        != os.path.normcase(os.path.normpath(str(bin_dir)))
    ]
    if dry_run:
        return "would remove %s from the user PATH" % bin_dir
    with winreg.OpenKey(
        winreg.HKEY_CURRENT_USER, "Environment", 0, winreg.KEY_SET_VALUE
    ) as key:
        winreg.SetValueEx(key, "Path", 0, kind, os.pathsep.join(keep))
    _broadcast_environment_change()
    return "removed %s from the user PATH" % bin_dir


def remove_from_posix_path(
    bin_dir: Path,
    env: Mapping[str, str],
    dry_run: bool = False,
    home: Optional[Path] = None,
) -> str:
    """Drop the marker line this collection appended, and the export after it.

    The profile is the user's file and may have grown a great deal since; it is
    copied into `.skills-backups` before a single line is touched.
    """
    profile = profile_for(env, home)
    absent = "%s has no PATH line from this collection" % profile
    if not profile.is_file():
        return absent
    text = profile.read_text(encoding="utf-8")
    if PROFILE_MARKER not in text:
        return absent
    if dry_run:
        return "would remove the PATH line from %s" % profile
    lines = text.splitlines(keepends=True)
    kept = []
    index = 0
    while index < len(lines):
        if lines[index].strip() == PROFILE_MARKER:
            index += 1
            if index < len(lines) and lines[index].lstrip().startswith("export PATH="):
                index += 1
            continue
        kept.append(lines[index])
        index += 1
    # Anchored on a notional "profile" root inside the home rather than on the
    # profile's own directory: that directory *is* the home, and backup_path
    # writes beside its root, which would put the copy in /home.
    backup = install.backup_path(profile.parent / "profile", profile.name)
    backup.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(str(profile), str(backup))
    profile.write_text("".join(kept), encoding="utf-8")
    return "removed the PATH line from %s (backup: %s)" % (profile, backup)


def command_remove_path(args: argparse.Namespace) -> int:
    bin_dir = (args.bin or DEFAULT_BIN).expanduser()
    for path, status in remove_shims(REPO_ROOT, bin_dir, args.dry_run):
        print("%-12s %s" % (status, path))
    if args.add_path:
        if os.name == "nt":
            print(remove_from_windows_path(bin_dir, args.dry_run))
        else:
            print(remove_from_posix_path(bin_dir, os.environ, args.dry_run))
    print("Open a new terminal for the change to take effect.")
    return 0


def install_argv(
    names: Sequence[str],
    scope: str,
    project_dir: Path,
    agents: Sequence[str],
    mode: str,
    force: bool,
    dry_run: bool,
) -> list:
    """Build the `install.py` argument list this subcommand delegates to."""
    argv = [
        "--non-interactive",
        "--scope",
        scope,
        "--project-dir",
        str(project_dir),
        "--mode",
        mode,
    ]
    for agent in agents:
        argv.extend(("--agent", agent))
    for name in names:
        argv.extend(("--skill", name))
    if force:
        argv.append("--force")
    if dry_run:
        argv.append("--dry-run")
    return argv


def uninstall_argv(
    names: Sequence[str],
    scope: str,
    project_dir: Path,
    agents: Sequence[str],
    *,
    all_skills: bool = False,
    global_instructions: bool = False,
    olympus: bool = False,
    shims: bool = False,
    external: Sequence[str] = (),
    unrecorded: bool = False,
    restore: bool = True,
    backup: bool = True,
    restore_from: Optional[Path] = None,
    dry_run: bool = False,
) -> list:
    """Build the `install.py --uninstall` argument list this command delegates to."""
    argv = [
        "--non-interactive",
        "--uninstall",
        "--scope",
        scope,
        "--project-dir",
        str(project_dir),
    ]
    for agent in agents:
        argv.extend(("--agent", agent))
    for name in names:
        argv.extend(("--skill", name))
    if all_skills:
        argv.append("--all")
    if global_instructions:
        argv.append("--global-instructions")
    if olympus:
        argv.append("--olympus")
    if shims:
        argv.append("--setup-path")
    for name in external:
        argv.append("--%s" % name)
    if unrecorded:
        argv.append("--unrecorded")
    if not restore:
        argv.append("--no-restore")
    if not backup:
        argv.append("--no-backup")
    if restore_from is not None:
        argv.extend(("--restore-from", str(restore_from)))
    if dry_run:
        argv.append("--dry-run")
    return argv


def can_prompt() -> bool:
    return install.is_terminal(sys.stdin) and install.is_terminal(sys.stdout)


def _dedup(roots: Sequence[Path]) -> list:
    seen: list = []
    for root in roots:
        if root not in seen:
            seen.append(root)
    return seen


def open_dashboard(
    project_dir: Path,
    scope: str = "project",
    agents: Optional[Sequence[str]] = None,
    mode: str = "copy",
    guided: Optional[bool] = None,
    pane: str = "skills",
    home: Optional[Path] = None,
) -> int:
    """Launch the Textual dashboard, or explain how to get it.

    `guided=None` lets the app decide: a destination with no install receipt
    gets the step-by-step flow, everything else gets the dashboard. This is the
    only place this module imports Textual, so `status` and `uninstall` keep
    working on a machine that does not have it.
    """
    try:
        import skills_tui
    except ImportError as exc:  # pragma: no cover - depends on the environment
        raise install.InstallError(
            "the dashboard needs Textual (%s). Run this through uv, which "
            "provisions the locked environment automatically, or "
            "`pip install textual`. Naming skills directly -- "
            "`skills install NAME` -- needs no dependencies at all." % exc
        )
    return skills_tui.run(project_dir, scope, agents, mode, guided, pane, home)


def command_list(args: argparse.Namespace) -> int:
    print("\n".join(install.available_skills()))
    return 0


def command_where(args: argparse.Namespace) -> int:
    print(REPO_ROOT)
    return 0


def command_install(args: argparse.Namespace) -> int:
    bundled = install.available_skills()
    names = list(args.name)
    if args.all:
        if names:
            raise install.InstallError("pass skill names or --all, not both")
        names = list(bundled)

    scope = "user" if args.user else "project"
    project_dir = args.project_dir.expanduser().resolve()
    if scope == "project" and not project_dir.is_dir():
        raise install.InstallError("project directory does not exist: %s" % project_dir)

    if not names:
        if not can_prompt():
            raise install.InstallError(
                "name at least one skill, or pass --all: there is no terminal "
                "to open the dashboard in, and installing every skill by "
                "default would put more in this project than you asked for. "
                "`skills list` shows what is available."
            )
        return open_dashboard(
            project_dir, scope, args.agent, args.mode, args.guided
        )

    unknown = sorted(set(names) - set(bundled))
    if unknown:
        raise install.InstallError("unknown skill: %s" % ", ".join(unknown))

    if scope == "user":
        # Some skills opt out of a machine-wide default because their
        # description costs every unrelated session context for no benefit.
        narrow = [name for name in names if not install.skill_global_default(name)]
        if narrow:
            print(
                "note: %s is not recommended machine-wide; it is meant for "
                "repo-level installs" % ", ".join(narrow),
                file=sys.stderr,
            )
    elif project_dir == REPO_ROOT:
        print(
            "note: installing into this collection's own checkout; "
            "run this from a project directory instead",
            file=sys.stderr,
        )

    return install.main(
        install_argv(
            names,
            scope,
            project_dir,
            args.agent,
            args.mode,
            args.force,
            args.dry_run,
        )
    )


def add_discovery_args(sub: argparse.ArgumentParser) -> None:
    """The arguments that decide *where* a command looks.

    Shared by `status` and `doctor` so the two sweep identically: a machine
    with an inconsistency the doctor reports must be one whose status lists the
    same install.
    """
    sub.add_argument(
        "--project-dir",
        type=Path,
        action="append",
        default=None,
        metavar="DIR",
        help="a project to sweep (repeatable; default the current directory)",
    )
    sub.add_argument(
        "--root",
        type=Path,
        action="append",
        default=[],
        metavar="DIR",
        help="a skills root to sweep outright (repeatable)",
    )
    sub.add_argument(
        "--no-registry",
        action="store_true",
        help="skip the roots earlier installs recorded; look only where told",
    )
    sub.add_argument("--home", type=Path, default=None, help=argparse.SUPPRESS)


def _project_dirs(args: argparse.Namespace) -> list:
    return [
        path.expanduser().resolve() for path in (args.project_dir or [Path.cwd()])
    ]


def command_status(args: argparse.Namespace) -> int:
    home = (args.home or Path.home()).expanduser()
    scope = "user" if args.user else "project"
    roots: list = []
    for project in _project_dirs(args):
        roots.extend(install.resolve_roots(args.agent, scope, home, project, None))
    roots.extend(path.expanduser().resolve() for path in args.root)
    if not args.no_registry:
        # Every root an earlier install recorded, so a project or --target
        # destination is found again without being named a second time.
        roots.extend(install.known_roots(home))
    print(
        install.format_status(
            install.discover(_dedup(roots), home, (args.bin or DEFAULT_BIN).expanduser())
        )
    )
    return 0


def command_doctor(args: argparse.Namespace) -> int:
    """Report what disagrees with itself, and optionally repair it.

    Exit code 3 when findings remain after the run: a script can tell "checked,
    all well" from "checked, still wrong" without parsing anything.
    """
    if args.json and args.fix is not None:
        raise install.InstallError(
            "--json reports and --fix changes things; run them one at a time"
        )
    home = (args.home or Path.home()).expanduser()
    extra = [path.expanduser().resolve() for path in args.root]
    projects = _project_dirs(args)
    swept = inventory.scan(home, projects, extra, not args.no_registry)
    results = inventory.findings(swept, args.include_foreign)

    if args.prune:
        dropped = install.forget_roots(home, swept.missing_roots, args.dry_run)
        for root in dropped:
            print("%s %s" % ("would forget" if args.dry_run else "forgot     ", root))
        if not dropped:
            print("no recorded root is missing")

    if args.json:
        print(json.dumps(inventory.report_json(swept, results), indent=2))
    elif args.fix is None:
        inventory.render_report(swept, results, include_foreign=args.include_foreign)
    else:
        kinds = list(args.fix)
        unknown = [kind for kind in kinds if kind not in inventory.KINDS]
        if unknown:
            raise install.InstallError(
                "unknown finding kind: %s; known: %s"
                % (", ".join(unknown), ", ".join(inventory.KINDS))
            )
        chosen = [
            finding for finding in results if not kinds or finding.kind in kinds
        ]
        if not chosen:
            print("nothing to fix")
        for finding in chosen:
            for line in inventory.apply_resolution(finding.resolutions[0], args.dry_run):
                print(line)
        # Nothing is cached: the second scan is the only honest answer to
        # "did that work", and a dry run legitimately still reports everything.
        swept = inventory.scan(home, projects, extra, not args.no_registry)
        results = inventory.findings(swept, args.include_foreign)
        print(
            "%d inconsistenc%s left" % (len(results), "y" if len(results) == 1 else "ies")
            if results
            else "nothing inconsistent is left"
        )

    return 0 if args.exit_zero or not results else 3


def command_uninstall(args: argparse.Namespace) -> int:
    names = list(args.name)
    if args.all and names:
        raise install.InstallError("pass skill names or --all, not both")
    external = list(args.external or [])
    if not (
        names
        or args.all
        or args.global_instructions
        or args.olympus
        or args.shims
        or external
    ):
        raise install.InstallError(
            "name at least one skill, or pass --all, --global-instructions, "
            "--olympus, --shims, or --external NAME. `skills status` lists what "
            "is installed and `skills manage` removes it interactively."
        )
    return install.main(
        uninstall_argv(
            names,
            "user" if args.user else "project",
            args.project_dir.expanduser().resolve(),
            args.agent,
            all_skills=args.all,
            global_instructions=args.global_instructions,
            olympus=args.olympus,
            shims=args.shims,
            external=external,
            unrecorded=args.unrecorded,
            restore=not args.no_restore,
            backup=not args.no_backup,
            restore_from=args.restore_from,
            dry_run=args.dry_run,
        )
    )


def command_manage(args: argparse.Namespace) -> int:
    if not can_prompt():
        raise install.InstallError(
            "skills manage needs an interactive terminal; use `skills status` "
            "for the same list as text"
        )
    return open_dashboard(
        args.project_dir.expanduser().resolve(),
        "user" if args.user else "project",
        args.agent,
        "copy",
        pane="manage",
        home=args.home,
    )


def command_setup_path(args: argparse.Namespace) -> int:
    bin_dir = (args.bin or DEFAULT_BIN).expanduser()
    for path, status in write_shims(REPO_ROOT, bin_dir, args.dry_run):
        print("%-12s %s" % (status, path))

    if path_contains(bin_dir, os.environ):
        print("%s is already on PATH." % bin_dir)
        return 0

    if args.add_path:
        if os.name == "nt":
            print(add_to_windows_path(bin_dir, args.dry_run))
        else:
            print(add_to_posix_path(bin_dir, os.environ, args.dry_run))
        print("Open a new terminal for the change to take effect.")
        return 0

    print()
    print("%s is not on PATH. Add it with:" % bin_dir)
    print()
    print("    skills setup-path --add-path")
    print()
    if os.name == "nt":
        print("That edits the current user's PATH in the registry (not the")
        print("machine-wide value) and leaves an existing PATH of any length intact.")
    else:
        print('Or add `export PATH="%s:$PATH"` to your shell profile.' % bin_dir)
    return 0


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(
        prog="skills",
        description=(
            "Install skills from this collection into the current project, "
            "from any directory."
        ),
    )
    result.add_argument("--version", action="version", version="skills %s" % install.VERSION)
    subcommands = result.add_subparsers(dest="command")

    installer = subcommands.add_parser(
        "install",
        help="install skills into the current directory (repo-level by default)",
    )
    installer.add_argument("name", nargs="*", help="skill names; omit to choose interactively")
    installer.add_argument("--all", action="store_true", help="install every bundled skill")
    installer.add_argument(
        "--user",
        action="store_true",
        help="install machine-wide instead of into the project directory",
    )
    installer.add_argument("--project-dir", type=Path, default=Path.cwd())
    installer.add_argument(
        "--agent",
        action="append",
        default=[],
        metavar="NAME",
        help="universal, codex, cursor, copilot, claude, or all (repeatable; default all)",
    )
    installer.add_argument("--mode", choices=("copy", "link"), default="copy")
    guided = installer.add_mutually_exclusive_group()
    guided.add_argument(
        "--guided",
        dest="guided",
        action="store_true",
        help="force the step-by-step flow instead of the dashboard",
    )
    guided.add_argument(
        "--no-guided",
        dest="guided",
        action="store_false",
        help="go straight to the dashboard on a first install",
    )
    installer.set_defaults(guided=None)
    installer.add_argument("--force", action="store_true")
    installer.add_argument("--dry-run", action="store_true")
    installer.set_defaults(handler=command_install)

    listing = subcommands.add_parser("list", help="list bundled skills")
    listing.set_defaults(handler=command_list)

    where = subcommands.add_parser("where", help="print this checkout's path")
    where.set_defaults(handler=command_where)

    setup = subcommands.add_parser(
        "setup-path", help="write launcher shims so `skills` works from any directory"
    )
    setup.add_argument(
        "--bin",
        type=Path,
        default=None,
        metavar="DIR",
        help="directory to write the launchers into (default ~/.local/bin)",
    )
    setup.add_argument(
        "--add-path",
        action="store_true",
        help="also add that directory to your PATH",
    )
    setup.add_argument("--dry-run", action="store_true")
    setup.set_defaults(handler=command_setup_path)

    status = subcommands.add_parser(
        "status", help="list what this collection installed, and where"
    )
    status.add_argument(
        "--user",
        action="store_true",
        help="report the machine-wide roots instead of the project directory's",
    )
    status.add_argument(
        "--agent", action="append", default=[], metavar="NAME",
        help="universal, codex, cursor, copilot, claude, or all (repeatable; default all)",
    )
    status.add_argument(
        "--bin", type=Path, default=None, metavar="DIR",
        help="directory holding the launcher shims (default ~/.local/bin)",
    )
    add_discovery_args(status)
    status.set_defaults(handler=command_status)

    doctor = subcommands.add_parser(
        "doctor", help="report installs that disagree with this checkout"
    )
    add_discovery_args(doctor)
    doctor.add_argument(
        "--include-foreign",
        action="store_true",
        help="also compare skills this checkout has no source for",
    )
    doctor.add_argument("--json", action="store_true", help="print the report as JSON")
    doctor.add_argument(
        "--exit-zero",
        action="store_true",
        help="exit 0 even when inconsistencies remain (the default is 3)",
    )
    doctor.add_argument(
        "--prune",
        action="store_true",
        help="forget recorded roots that no longer exist",
    )
    doctor.add_argument(
        "--fix",
        nargs="*",
        default=None,
        metavar="KIND",
        help=(
            "apply the default fix for every finding, or only for the named "
            "kinds: %s" % ", ".join(inventory.KINDS)
        ),
    )
    doctor.add_argument("--dry-run", action="store_true")
    doctor.set_defaults(handler=command_doctor)

    remover = subcommands.add_parser(
        "uninstall", help="remove installed skills, instructions, or shims"
    )
    remover.add_argument("name", nargs="*", help="skill names to remove")
    remover.add_argument(
        "--all", action="store_true", help="every skill recorded in the resolved roots"
    )
    remover.add_argument(
        "--user",
        action="store_true",
        help="remove from the machine-wide roots instead of the project directory's",
    )
    remover.add_argument("--project-dir", type=Path, default=Path.cwd())
    remover.add_argument(
        "--agent", action="append", default=[], metavar="NAME",
        help="universal, codex, cursor, copilot, claude, or all (repeatable; default all)",
    )
    remover.add_argument(
        "--global-instructions",
        action="store_true",
        help="also remove ~/.agents/AGENTS.md and ~/.claude/CLAUDE.md",
    )
    remover.add_argument(
        "--olympus",
        action="store_true",
        help=(
            "also remove the olympus MCP server from ~/.claude.json, leaving "
            "every other server there; the reporting skill is removed by name"
        ),
    )
    remover.add_argument(
        "--shims", action="store_true", help="also remove the `skills` launchers"
    )
    remover.add_argument(
        "--external",
        action="append",
        default=[],
        metavar="NAME",
        choices=install.EXTERNAL_NAMES,
        help="an external tool: %s (repeatable)" % ", ".join(install.EXTERNAL_NAMES),
    )
    remover.add_argument(
        "--unrecorded",
        action="store_true",
        help="also remove skill directories no receipt records",
    )
    remover.add_argument(
        "--no-restore",
        action="store_true",
        help="leave any pre-install original in .skills-backups",
    )
    remover.add_argument(
        "--no-backup",
        action="store_true",
        help="delete rather than move aside (unrecoverable)",
    )
    remover.add_argument(
        "--restore-from",
        type=Path,
        default=None,
        metavar="PATH",
        help="with exactly one skill name: restore this backup in its place",
    )
    remover.add_argument("--dry-run", action="store_true")
    remover.set_defaults(handler=command_uninstall)

    manage = subcommands.add_parser(
        "manage", help="open the dashboard on the manage pane"
    )
    manage.add_argument("--user", action="store_true")
    manage.add_argument("--project-dir", type=Path, default=Path.cwd())
    manage.add_argument(
        "--agent", action="append", default=[], metavar="NAME",
        help="universal, codex, cursor, copilot, claude, or all (repeatable; default all)",
    )
    manage.add_argument("--home", type=Path, default=None, help=argparse.SUPPRESS)
    manage.set_defaults(handler=command_manage)

    return result


def main(argv: Optional[Sequence[str]] = None) -> int:
    raw = list(sys.argv[1:] if argv is None else argv)
    arguments = parser().parse_args(raw)
    try:
        if getattr(arguments, "handler", None) is None:
            # A bare `skills` in a terminal means "show me what I have"; without
            # one there is nothing to show, so fall back to the help text.
            if not raw and can_prompt():
                return open_dashboard(Path.cwd())
            parser().print_help()
            return 2
        return arguments.handler(arguments)
    except KeyboardInterrupt:
        print("error: interrupted", file=sys.stderr)
        return 130
    except install.InstallError as exc:
        print("error: %s" % exc, file=sys.stderr)
        return 2
    except OSError as exc:
        print("error: %s" % exc, file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
