// Ticket #8 — Markdown walkthrough. cohort → sub-group → layer → symbol (name (kind) — file:line).
import type { Analysis, SubGroup } from "./types.ts";

const short = (k: string) =>
  ({ FunctionDeclaration: "fn", MethodDeclaration: "method", ClassDeclaration: "class",
     InterfaceDeclaration: "interface", TypeAliasDeclaration: "type", EnumDeclaration: "enum",
     VariableDeclaration: "const" } as Record<string, string>)[k] ?? k;

const LAYER = (l: number) => (l === 0 ? "Foundational" : `Layer ${l}`);

function renderGroup(sg: SubGroup, n: number): string {
  const lines: string[] = [];
  const badges = sg.pkgs.map((p) => `\`${p}\``).join(" ") + (sg.crossPkg ? " · **cross-package**" : "");
  lines.push(`### ${n}. ${sg.title ?? "Changes"}`);
  lines.push(`${sg.symbols.length} symbols · ${badges} · \`group:${sg.id}\``);
  if (sg.summary) lines.push(`\n${sg.summary}`);
  const byLayer = new Map<number, typeof sg.symbols>();
  for (const s of sg.symbols) (byLayer.get(s.layer) ?? byLayer.set(s.layer, []).get(s.layer)!).push(s);
  for (const L of [...byLayer.keys()].sort((a, b) => a - b)) {
    lines.push(`\n**${LAYER(L)}**`);
    for (const s of byLayer.get(L)!) lines.push(`- \`${s.name}\` (${short(s.kind)}) — ${s.file}:${s.line}`);
  }
  return lines.join("\n");
}

export function render(a: Analysis): string {
  const m = a.meta;
  const out: string[] = [];
  out.push(`# PR walkthrough`);
  out.push(`_${m.repo} · \`${m.base.slice(0, 12)}\`..\`${m.head.slice(0, 12)}\`_`);
  out.push("");
  out.push(
    `**${m.symbolCount}** changed symbols · **${m.edgeCount}** dependency edges ` +
    `(${m.crossFile} cross-file, ${m.crossPkg} cross-package) · **${a.subGroups.length}** groups · ` +
    `analyzed in ${(m.analyzeMs / 1000).toFixed(1)}s`,
  );
  out.push("");
  out.push("> Changes are reorganized from the flat diff into dependency groups, each ordered " +
    "foundational-first. Read top to bottom.");
  out.push("");

  // Product changes first, under cohort headings; verification (tests) last.
  const testGroups = a.subGroups.filter((g) => g.isTest);
  const productGroups = a.subGroups.filter((g) => !g.isTest);
  const isSingleUnlinked = (g: SubGroup) => g.symbols.length === 1 && g.symbols[0].degree === 0;
  const productSingles = productGroups.filter(isSingleUnlinked);
  const collapse = productSingles.length > 3;

  let lastCohort = -1, n = 0;
  for (const sg of productGroups) {
    if (collapse && isSingleUnlinked(sg)) continue; // routed to the Unlinked section
    if (sg.cohortId !== lastCohort) { out.push(`\n## Cohort ${sg.cohortId + 1}`); lastCohort = sg.cohortId; }
    out.push(""); out.push(renderGroup(sg, ++n));
  }

  if (collapse) {
    out.push(`\n## Unlinked changes`);
    out.push(`Changed symbols with no dependency to another changed symbol:`);
    for (const g of productSingles) { const s = g.symbols[0]; out.push(`- \`${s.name}\` (${short(s.kind)}) — ${s.file}:${s.line}`); }
  }

  if (testGroups.length) {
    out.push(`\n## Verification / tests`);
    out.push(`Test changes — read last.`);
    for (const sg of testGroups) { out.push(""); out.push(renderGroup(sg, ++n)); }
  }
  out.push("");
  out.push(`---\n_Generated by semantic-pr · spec: docs/layered-semantic-pr-spec.md_`);
  return out.join("\n");
}
