#!/usr/bin/env bash
# Install version-controlled agent skills into every agent's user-scope skill
# directory. Agent-neutral and reusable: any coding agent that can run a startup
# script — or a person, by hand — can invoke this to make the skills
# discoverable. Dependency-free (git + coreutils), idempotent, non-interactive.
#
# Source, tried in order:
#   1. Local  — if $AGENT_SKILLS_PROJECT_DIR/$AGENT_SKILLS_SUBDIR contains
#               <skill>/SKILL.md entries, install from there (no network/auth).
#   2. Clone  — otherwise clone $AGENT_SKILLS_REPO@$AGENT_SKILLS_REF.
#
# Destinations: every path in $AGENT_SKILLS_DEST (colon-separated). The default
# covers both user-scope discovery roots used across agents:
#   ~/.claude/skills    Claude Code
#   ~/.agents/skills    shared Agent Skills dir (Codex, Cursor, Copilot)
#
# Config (all optional):
#   AGENT_SKILLS_REPO        owner/name of the source repo   (default dm1681/skills)
#   AGENT_SKILLS_REF         branch or tag                    (default main)
#   AGENT_SKILLS_SUBDIR      dir holding <skill>/SKILL.md      (default skills)
#   AGENT_SKILLS_DEST        colon-separated destination roots
#   AGENT_SKILLS_PROJECT_DIR repo to check for local skills   (default PWD)
#
# User-level instructions (opt-in, off by default). Set
# AGENT_GLOBAL_INSTRUCTIONS to `link` or `copy` to also install
# $SUBDIR/../global/AGENTS.md as machine-wide guidance:
#   link   ~/.claude/CLAUDE.md -> ~/.agents/AGENTS.md -> the local checkout
#   copy   ~/.agents/AGENTS.md holds the text; ~/.claude/CLAUDE.md points to it
# `link` needs a durable source, so a cloned source is always installed as
# `copy` — the clone lives in a temporary directory that disappears on exit.
#   AGENT_GLOBAL_INSTRUCTIONS  off (default) | link | copy
#   AGENT_GLOBAL_AGENTS_FILE   default ~/.agents/AGENTS.md
#   AGENT_GLOBAL_CLAUDE_FILE   default ~/.claude/CLAUDE.md
set -euo pipefail

REPO="${AGENT_SKILLS_REPO:-dm1681/skills}"
REF="${AGENT_SKILLS_REF:-main}"
SUBDIR="${AGENT_SKILLS_SUBDIR:-skills}"
PROJECT_DIR="${AGENT_SKILLS_PROJECT_DIR:-$PWD}"
DEST_LIST="${AGENT_SKILLS_DEST:-${HOME}/.claude/skills:${HOME}/.agents/skills}"
GLOBAL_MODE="${AGENT_GLOBAL_INSTRUCTIONS:-off}"
GLOBAL_AGENTS_FILE="${AGENT_GLOBAL_AGENTS_FILE:-${HOME}/.agents/AGENTS.md}"
GLOBAL_CLAUDE_FILE="${AGENT_GLOBAL_CLAUDE_FILE:-${HOME}/.claude/CLAUDE.md}"
MANAGED_MARKER='<!-- dm1681/skills: managed file -->'

log() { echo "[skills-sync] $*" >&2; }

# Back up $1 (if present) beside the sibling .skills-backups dir the installer
# uses, then replace it with stdin.
write_managed() {
  local path="$1" dir name stamp backup tmp
  dir="$(dirname "$path")"
  name="$(basename "$path")"
  tmp="$dir/.$name.tmp"
  mkdir -p "$dir"
  cat >"$tmp"
  if [ -e "$path" ] || [ -L "$path" ]; then
    if cmp -s "$tmp" "$path"; then
      rm -f "$tmp"
      log "unchanged: $path"
      return 0
    fi
    stamp="$(date -u +%Y%m%dT%H%M%SZ)"
    backup="$(dirname "$dir")/.skills-backups/$(basename "$dir")/$name-$stamp"
    mkdir -p "$(dirname "$backup")"
    mv "$path" "$backup"
    log "backed up: $path -> $backup"
  fi
  mv "$tmp" "$path"
  log "installed: $path"
}

# Install user-level instructions from $1 (a global/AGENTS.md) in mode $2.
install_global_instructions() {
  local source="$1" mode="$2" header
  if [ ! -f "$source" ]; then
    log "WARNING: no global instructions at $source; skipped"
    return 0
  fi
  header="$MANAGED_MARKER
<!-- Generated by dm1681/skills. Edit $source and reinstall; -->
<!-- edits made here are backed up and replaced on the next run. -->
"
  if [ "$mode" = "copy" ]; then
    { printf '%s\n' "$header"; cat "$source"; } | write_managed "$GLOBAL_AGENTS_FILE"
  else
    printf '%s\n# Global agent instructions\n\nShared by every coding agent on this machine. The instructions are\nversion controlled and imported from the checkout that owns them:\n\n@%s\n\nAgents that do not resolve `@path` imports should read that file\ndirectly, or reinstall in copy mode to write the text into this file.\n' \
      "$header" "$source" | write_managed "$GLOBAL_AGENTS_FILE"
  fi
  printf '%s\n# Global instructions\n\nKept alongside the other agents'"'"' guidance so every tool on this machine\nloads the same instructions:\n\n@%s\n' \
    "$header" "$GLOBAL_AGENTS_FILE" | write_managed "$GLOBAL_CLAUDE_FILE"
}

# 0 if $1 contains <skill>/SKILL.md entries.
have_skills() {
  local m
  for m in "$1"/*/SKILL.md; do
    [ -e "$m" ] && return 0
  done
  return 1
}

# Copy one skill dir ($1) named ($2) into every destination root, replacing any
# existing copy of that skill name.
install_one() {
  local srcdir="$1" name="$2" dest
  printf '%s\n' "$DEST_LIST" | tr ':' '\n' | while IFS= read -r dest; do
    [ -n "$dest" ] || continue
    mkdir -p "$dest"
    rm -rf "${dest:?}/${name:?}"
    cp -R "$srcdir" "$dest/$name"
  done
}

# Install every <skill>/SKILL.md dir found under $1. Non-zero if none found.
install_from() {
  local src="$1" m dir name total=0
  for m in "$src"/*/SKILL.md; do
    [ -e "$m" ] || continue
    dir="$(dirname "$m")"
    name="$(basename "$dir")"
    install_one "$dir" "$name"
    total=$((total + 1))
    log "installed: $name"
  done
  log "installed $total skill(s) into: $DEST_LIST"
  [ "$total" -gt 0 ]
}

# 1) Local: skills already present in the current repo.
if have_skills "${PROJECT_DIR}/${SUBDIR}"; then
  log "source: local ${SUBDIR}/ in ${PROJECT_DIR}"
  install_from "${PROJECT_DIR}/${SUBDIR}" || log "no skills found locally"
  if [ "$GLOBAL_MODE" != "off" ]; then
    install_global_instructions "${PROJECT_DIR}/global/AGENTS.md" "$GLOBAL_MODE"
  fi
  exit 0
fi

# 2) Clone: fetch the source repo and install from it.
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
log "source: cloning ${REPO}@${REF}"
if git clone --depth 1 --branch "$REF" \
    "https://github.com/${REPO}.git" "$tmp/repo" \
    2>&1 | sed 's/^/[skills-sync] git: /' >&2; then
  install_from "$tmp/repo/${SUBDIR}" || log "no skills found in ${REPO}/${SUBDIR}"
  if [ "$GLOBAL_MODE" != "off" ]; then
    # The clone is deleted on exit, so a pointer into it would dangle.
    if [ "$GLOBAL_MODE" = "link" ]; then
      log "cloned source: installing global instructions as copy"
    fi
    install_global_instructions "$tmp/repo/global/AGENTS.md" copy
  fi
else
  log "WARNING: could not clone ${REPO} (a private source repo must be reachable"
  log "         from this session, or vendor the skills locally). Skills not"
  log "         installed; session will continue."
fi

exit 0
